name: uit_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.9.1
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  hive_flutter: ^1.1.0
  home_widget: ^0.9.0
  intl: ^0.20.2
  json_annotation: ^4.11.0
  riverpod_annotation: ^4.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
